language: node_js

cache:
  directories:
  - node_modules

node_js:
  - '8'

dist: trusty

addons:
  apt:
    packages:
      - google-chrome-stable
  firefox: 'latest-esr'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.2
  - export PATH=$HOME/.yarn/bin:$PATH
  - tar -xjf /tmp/firefox-latest-esr.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - export CHROME_BIN=google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn ci-check

after_success:
  - yarn semantic-release

notifications:
  email: false
