language: node_js

node_js:
  - '8'

notifications:
  email: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile@1

install:
  # Enforce installing dependencies from our offline cache instead of going out
  # to the live registry to download code
  - yarn install --offline

before_script: greenkeeper-lockfile-update

script:
  - yarn ci-check

after_script: greenkeeper-lockfile-upload

after_success:
  - yarn semantic-release

before_deploy:
  - yarn build-storybook

deploy:
  skip_cleanup: true
  provider: cloudfoundry
  username: apikey
  password: $CLOUD_API_KEY
  api: https://api.ng.bluemix.net
  organization: carbon-design-system
  space: production
  on:
    branch: master
