version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
            export PATH=$HOME/.yarn/bin:$PATH
      - run:
          name: Install dependencies from offline mirror
          command: yarn install --offline
      - run:
          name: Run Continuous Integration checks
          command: yarn ci-check
      - deploy:
          name: deploy to IBM Cloud
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # Install `ibmcloud` CLI
              curl -fsSL https://clis.ng.bluemix.net/install/linux | sh

              # Login and push staging manifest
              ibmcloud login \
                --apikey $CLOUD_API_KEY \
                -a https://api.ng.bluemix.net \
                -o carbon-design-system \
                -s production

              ibmcloud cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
              ibmcloud cf install-plugin blue-green-deploy -f -r CF-Community

              # Default storybook build
              yarn build-storybook

              ibmcloud cf blue-green-deploy carbon-storybook \
                -f .circleci/manifest.yml \
                --delete-old-apps

              # Experimental storybook build
              rm -rf storybook-static
              CARBON_USE_EXPERIMENTAL_FEATURES=true yarn build-storybook

              ibmcloud cf blue-green-deploy carbon-storybook-experimental \
                -f .circleci/manifest.experimental.yml \
                --delete-old-apps
            fi
