name: Add Review Labels
on: pull_request_review
jobs:
  reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: ./actions/add-review-labels
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTO_LABEL_USERS: 'asudoh,emyarod,tw15egan'
