name: Add To Project
on:
  issues:
    types: [opened, labeled]
  workflow_call:
    secrets:
      ADD_TO_PROJECT_PAT:
        required: true

env:
  DESIGN_SYSTEM_PROJECT_URL: https://github.com/orgs/carbon-design-system/projects/39
  PROPOSALS_PROJECT_URL: https://github.com/orgs/carbon-design-system/projects/51
  TYPESCRIPT_PROJECT_URL: https://github.com/orgs/carbon-design-system/projects/53
  LABEL_ENHANCEMENT: 'type: enhancement ðŸ’¡'
  LABEL_TYPESCRIPT: 'area: typescript'

jobs:
  add-to-proposals-project:
    name: Add issue with enhancement label to the Proposals project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@31b3f3ccdc584546fc445612dec3f38ff5edb41c #v0.5.0
        with:
          labeled: ${{ env.LABEL_ENHANCEMENT }}
          project-url: ${{ env.PROPOSALS_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}

  add-to-typescript-project:
    name: Add issue with typescript label to the TypeScript Adoption project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@31b3f3ccdc584546fc445612dec3f38ff5edb41c #v0.5.0
        with:
          labeled: ${{ env.LABEL_TYPESCRIPT }}
          project-url: ${{ env.TYPESCRIPT_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}

  add-to-design-system-project:
    name: Add issue to the Design System project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@31b3f3ccdc584546fc445612dec3f38ff5edb41c #v0.5.0
        with:
          labeled: ${{ env.LABEL_ENHANCEMENT }}, ${{ env.LABEL_TYPESCRIPT }}
          label-operator: NOT
          project-url: ${{ env.DESIGN_SYSTEM_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
