name: Add Review Labels
on: pull_request_review
jobs:
  reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./actions/add-review-labels
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTO_LABEL_USERS: 'asudoh,emyarod,tw15egan'
