name: Contribution triage - enhancement created
on:
  issues:
    types: [labeled, opened]

permissions:
  issues: write

jobs:
  add-comment:
    name:
      If new enhancement issue is submitted, then post the following comment.
    runs-on: ubuntu-latest
    if:
      ${{ contains(github.event.label.name, format('type{0} enhancement ðŸ’¡', ':')) }}
    steps:
      - name: Log github event
        env:
          $GITHUB_CONTEXT_LABELS: ${{ toJson(github.event.label) }}
        run: echo "$GITHUB_CONTEXT_LABELS"
      - name: Add comment
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 #v6.4.1
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you for submitting a feature request. Your proposal is open and will soon be triaged by the Carbon team. 
              
              If your proposal is accepted and the Carbon team has bandwidth they will take on the issue, or else request you or other volunteers from the community to work on this issue.'
            })
