name: 'DCO Assistant'
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]
  merge_group:
    types: [checks_requested]

jobs:
  DCO:
    runs-on: ubuntu-latest
    steps:
      - name: 'DCO Assistant'
        if:
          (github.event.comment.body == 'recheck' || github.event.comment.body
          == 'I have read the DCO document and I hereby sign the DCO.') ||
          github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@ca4a40a7d1004f18d9960b404b97e5f30a505a08 # v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'dco-signatures.json'
          path-to-document: 'https://github.com/carbon-design-system/carbon-dco/blob/main/dco.md'
          branch: 'main'
          allowlist: bot*
          remote-organization-name: carbon-design-system
          remote-repository-name: carbon-dco
          create-file-commit-message:
            'chore: create file to store dco signatures'
          signed-commit-message:
            'chore: $contributorName has signed the dco in #$pullRequestNo'
          custom-notsigned-prcomment:
            'Thanks for your submission! We ask that $you sign our [Developer
            Certificate of
            Origin](https://github.com/carbon-design-system/carbon-dco/blob/main/dco.md)
            before we can accept your contribution. You can sign the DCO by
            adding a comment below using this text:'
          custom-pr-sign-comment:
            'I have read the DCO document and I hereby sign the DCO.'
          custom-allsigned-prcomment: 'All contributors have signed the DCO.'
          lock-pullrequest-aftermerge: false
          use-dco-flag: true
