name: Deploy React storybook to IBM Cloud

on:
  workflow_dispatch:
  push:
    tags:
      # Matches tags that have the shape `vX.Y.Z`. Reference:
      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#onpushpull_requesttagsbranches
      - 'v[0-9]+.[0-9]+.[0-9]+'

      # Ignore tags that use a preid after `vX.Y.Z`, for example: vX.Y.Z-alpha.0
      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#example-using-positive-and-negative-patterns
      - '!v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@main
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build project
        run: yarn build
      - name: Install ibmcloud CLI
        run: curl -fsSL https://clis.cloud.ibm.com/install/osx | sh
      - name: Login to IBM Cloud
        env:
          CLOUD_API_KEY: ${{ secrets.CLOUD_API_KEY}}
        run: |
          ibmcloud login \
            -a 'https://cloud.ibm.com' \
            --apikey "$CLOUD_API_KEY" \
            -r 'us-south'
          ibmcloud target -o 'carbon-design-system' -s 'production'
      - name: Install IBM Cloud plugins
        run: |
          ibmcloud cf install
          ibmcloud cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
          ibmcloud cf install-plugin blue-green-deploy -f -r CF-Community
      - name: Deploy React storybook
        run: |
          cd packages/react
          yarn build-storybook
          ibmcloud cf blue-green-deploy carbon-storybook \
            -f manifest.yml \
            --delete-old-apps
