name: Deploy Web Components storybook to GH pages

on:
  workflow_dispatch:
  push:
    tags:
      # Matches tags that have the shape `vX.Y.Z`. Reference:
      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#onpushpull_requesttagsbranches
      - 'v[0-9]+.[0-9]+.[0-9]+'

      # Ignore tags that use a preid after `vX.Y.Z`, for example: vX.Y.Z-alpha.0
      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#example-using-positive-and-negative-patterns
      - '!v[0-9]+.[0-9]+.[0-9]+-*'
      - '!v10*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest-larger-disk
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build project
        run: yarn build
      - name: Build static Web Components storybook
        run: |
          cd packages/web-components
          yarn storybook:build
      - name: Create CNAME
        run: |
          touch packages/web-components/storybook-static/.nojekyll
          touch packages/web-components/storybook-static/CNAME
          echo "web-components.carbondesignsystem.com" > packages/web-components/storybook-static/CNAME
      - name: Push to Web Components repo
        uses: cpina/github-action-push-to-another-repository@55306faa4ed53b815ae49e564af8cfb359d32ae2 #v1.7.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          source-directory: 'packages/web-components/storybook-static'
          destination-github-username: 'carbon-design-system'
          destination-repository-name: 'carbon-web-components-storybook-v2'
          user-name: carbon-bot
          user-email: carbon@us.ibm.com
          target-branch: main
          commit-message: 'chore(website): update to latest'
