name: Deploy Packages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Promote]
    types:
      - completed

jobs:
  design-language-website:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          repository: carbon-design-system/design-language-website
          ref: master
      - name: Use Node.js 20.x
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 #v4.0.0
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Update dependencies
        run: |
          yarn upgrade \
            @carbon/pictograms@next \
            @carbon/pictograms-react@next \
            @carbon/icons@next \
            @carbon/icons-react@next \
      - name: Generate token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a #v2.1.0
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: 'release/update-carbon-deps'
          commit-message: 'chore(release): update carbon deps'
          delete-branch: true
          title: 'chore(release): update carbon deps'
          token: ${{ steps.generate_token.outputs.token }}
          body: |
            Automated pull request to update Carbon on the website

            **Checklist**

            - [ ] Verify package version bumps are accurate
            - [ ] Verify CI passes as expected
            - [ ] Verify no regressions on the website in the deploy preview
  gatsby-theme-carbon:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          repository: carbon-design-system/gatsby-theme-carbon
          ref: main
      - name: Use Node.js 20.x
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 #v4.0.0
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Update dependencies
        run: |
          yarn workspace gatsby-theme-carbon up  \
            @carbon/elements \
            @carbon/grid \
            @carbon/themes \
            @carbon/pictograms-react \
            @carbon/react
      - name: Generate token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a #v2.1.0
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: 'release/update-carbon-deps'
          commit-message: 'chore(release): update carbon deps'
          delete-branch: true
          title: 'chore(release): update carbon deps'
          token: ${{ steps.generate_token.outputs.token }}
          body: |
            Automated pull request to update Carbon in gatsby-theme-carbon

            **Checklist**

            - [ ] Verify package version bumps are accurate
            - [ ] Verify CI passes as expected
            - [ ] Verify no regressions on the website in the deploy preview
