name: Issue Triage
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./actions/issues
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          enabled: true
  add-to-project:
  name: Add issue to Design System project
  runs-on: ubuntu-latest
  steps:
    - uses: actions/add-to-project@v0.0.3
      with:
        project-url: https://github.com/orgs/carbon-design-system/projects/39
        github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
