name: 'Issue Triage - Strategic Adopter'

on:
  issues:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    if: |
      !github.event.issue.pull_request
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 #v4.1.2
      - uses: actions-ecosystem/action-regex-match@9e6c4fb3d5e898f505be7a1fb6e7b0a278f6665b #v2.0.2
        id: regex-match
        with:
          text: ${{ github.event.issue.body }}
          regex:
            '\b(API Connect|Turbonomic|Instana|NS1|watsonx Orchestrate|watsonx
            Code Assistant|Planning Analytics|SPSS
            Statistics|watsonx.data|watsonx.ai|watsonx.governance|Maximo
            Application Suite|Environmental Intelligence Suite|Envizi ESG
            Suite|QRadar Log Insights|QRadar XDR/EDR (ReaQta)|Randori ASM|QRadar
            SIEM|MaaS360|Flash|Defender|Fusion|APP Connect|Apptio
            Cloudability|Apptio Targetprocess|AIOps Insights|Hybrid Cloud
            Mesh|Aspera|Blueworks Live|OpenPages|Databand.ai|Cognos
            Analytics|Sterling B2B Integration SaaS|Sterling Order & Inventory
            Management|Supply Chain Intelligence Suite|TRIRIGA Application
            Suite|QRadar SOAR|Guardium Insights|Verify on Cloud\b'
          flags: g
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['adopter: strategic-product']
            })
