name: 'Issue Triage - Strategic Adopter'

on:
  issues:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    if: |
      !github.event.issue.pull_request
    steps:
      - uses: actions/checkout@main
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.issue.body }}
          regex:
            '\b(Instana|QRadar|MaaS360|Environmental Intelligence Suite|Watson
            Orchestrate|Watson Assistant|Planning Analytics|ReaQta|API
            Connect|Fusion|Flash Storage|Envizi|Maximo|Turbonomic|Fusion
            Microsoft 360)|StepZen|APP Connect Enterprise|Watson
            Discovery|Watson Code Assistant|Hybrid Cloud Mesh|AIOps
            Insights|Databand|OpenPages|watsonx.data|watsonx.ai|watsonx.gov|QRadar
            Log Insights|QRadar XDR|QRadar EDR (ReaQta)|QRadar SOAR|Randori
            ASM|Guardium Insights|Trusteer Fraud Protection|Security Verify on
            Cloud|Sterling Data Exchange SaaS|TRIRIGA|Sterling Order and
            Inventory Management|Supply Chain Intelligence Suite\b'
          flags: g
      - uses: actions/github-script@v6
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['adopter: strategic-product']
            })
