name: Release Notifications

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  post-comments:
    name: Post notification comments on PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Generate token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a #v2.1.0
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Add release information on pull requests
        uses: ./actions/release-notifications
        with:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          OWNER: 'carbon-design-system'
          REPO_NAME: 'carbon'
          enabled: true
