name: Slack Office Hours Reminder - Design

on:
  workflow_dispatch:
  schedule:
    # Run every Monday at 09:00AM CT, 02:00PM UTC
    - cron: '0 14 * * MON'

jobs:
  post-reminder:
    name: Post design reminder to carbon-design-system and carbon-announcements
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "username": "Carbon Design System",
              "icon_url": "https://user-images.githubusercontent.com/3360588/192045905-5d9705af-92e2-4432-805e-15db98571e8b.png",
              "channel": "#carbon-design-system",
              "text": "Join us for Carbon Design Office Hours!",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Join us for Carbon Design Office Hours!",
                    "emoji": true
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "image",
                  "image_url":
                    "https://user-images.githubusercontent.com/77697351/207710625-c246e20f-90af-43e4-84a7-c35f75005503.jpg",
                  "alt_text": "Carbon Design Office Hours image"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":sparkles:  _Need visual or UX feedback on your design layouts from a Carbon perspective?_  \n\n :jigsaw:  _Want advice on how to use Carbon components or patterns?_  \n\n :rocket:  _Have questions about migrating from Carbon v10 to v11?_"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Carbon Design Office Hours* is a bi-weekly opportunity on Tuesdays at 10:00 am ET to discuss topics like these and to get help from the Carbon design team. Before sharing during office hours, we recommend sending your design files to us before the meeting, providing actual content in UI examples, and having design iterations or research on hand to help us give you actionable and constructive feedback."
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":yourlearning:  *Subscribe and add to your calendar*"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Subscribe",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "https://ec.yourlearning.ibm.com/w3/event/10522523",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":memo:  *Sign up to share and get help at a future session*"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View the agenda",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "https://ibm.biz/carbon-design-office-hours",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "divider"
                }
              ]
            }
