name: Send slack announcement

on:
  workflow_dispatch:
    inputs:
      text:
        required: true
        description: 'Announcement title'
        type: string
      channel:
        required: true
        description: 'Specify channels'
        type: string
      block-kit:
        required: true
        description: 'Copy and paste the block kit'
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.matrix.outputs.channel}}
    steps:
      - id: matrix
        run: |
          channels="${{ github.event.inputs.channel }}"
          echo "channel=[\"${channels//', '/\",\"}\"]" >> $GITHUB_OUTPUT

  slack-announcement:
    needs: [setup]
    name: Send slack announcement
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - name: Send slack announcement
        id: slack
        uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "username": "Carbon Design System",
              "icon_url": "https://user-images.githubusercontent.com/3360588/192045905-5d9705af-92e2-4432-805e-15db98571e8b.png",
              "channel": "${{ matrix.value }}",
              "text": "${{ github.event.inputs.text }}",
              "blocks": ${{ toJSON(fromJSON(github.event.inputs.block-kit).blocks) }}
            }
