name: Send slack announcement

on:
  workflow_dispatch:
    inputs:
      text: 
        required: true
        description: 'Announcement title'
        type: string
      channel:
        required: true
        description: 'Specify channels'
        type: string
      block-kit:
        required: true
        description: 'Copy and paste the block kit'
        type: string

jobs:
  slack-announcement:
    name: Send slack announcement
    runs-on: ubuntu-latest
    steps:
      - name: Send slack announcement
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # For posting a rich message using Block Kit
          channel-id: "${{ github.event.inputs.channel }}"
          payload: |
            {
              "username": "Carbon Design System",
              "icon_url": "https://user-images.githubusercontent.com/3360588/192045905-5d9705af-92e2-4432-805e-15db98571e8b.png",
              "text": "${{ github.event.inputs.text }}",
              "blocks": ${{ toJSON(fromJSON(github.event.inputs.block-kit).blocks) }}
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
