name: Sync generated files
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Build project
        run: yarn build
      - name: Sync project dependency files
        run: yarn sync
      - name: Push generated artifacts to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Our git status is not clean. Checking in the following files:";
            echo "$(git status --porcelain)";

            git config --global credential.helper 'cache --timeout=120'
            git config --global user.email "carbon@us.ibm.com"
            git config --global user.name "carbon-bot"

            git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/carbon-design-system/carbon.git"
            git checkout main
            git add -A
            git commit -m "chore(project): sync generated files"
            git push
          fi
