name: v10 - Deploy React storybook to IBM Cloud

on:
  workflow_dispatch:
  push:
    tags:
      # Matches tags that have the shape `v10.Y.Z`. Reference:
      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#onpushpull_requesttagsbranches
      - 'v10.[0-9]+.[0-9]+'

      # Ignore tags that use a preid after `vX.Y.Z`, for example: vX.Y.Z-alpha.0
      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#example-using-positive-and-negative-patterns
      - '!v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  build-ibmcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build project
        run: yarn build
      - name: Build static React storybook
        run: |
          cd packages/react
          yarn build-storybook
      - name: Create CNAME
        run: |
          touch packages/react/storybook-static/CNAME
          echo "v7-react.carbondesignsystem.com" > packages/react/storybook-static/CNAME
      - name: Push to v7 repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          source-directory: 'packages/react/storybook-static'
          destination-github-username: 'carbon-design-system'
          destination-repository-name: 'carbon-storybook-v7'
          user-name: carbon-bot
          user-email: carbon@us.ibm.com
          target-branch: main
          commit-message: 'chore(release):  ${{ github.ref }}'
